dependencies {
  implementation project(':infrastructure:async')
  implementation 'com.fasterxml.jackson.core:jackson-databind'
  implementation 'org.apache.tuweni:tuweni-bytes'

  testImplementation project(':infrastructure:test-support')
  testImplementation 'org.assertj:assertj-core'
  testImplementation 'org.mockito:mockito-core'
  testImplementation 'org.junit.jupiter:junit-jupiter-api'
  testImplementation 'org.junit.jupiter:junit-jupiter-engine'
}

description = 'Teku Attacker Client'